In [1]:
import pandas as pd
import numpy as np

In [2]:
#load data into dataframe
DF_0 = pd.read_csv("GeneratedBusinessData.csv")

In [3]:
#check for duplicates
print(DF_0[DF_0.duplicated()])

Empty DataFrame
Columns: [Business ID, Business State, Total Long-term Debt, Total Equity, Debt to Equity, Total Liabilities, Total Revenue, Profit Margin]
Index: []

In [4]:
#drop duplicates if they exist
DF_0.drop_duplicates(inplace=True)

In [5]:
#GROUP BY state and CALCULATE mean, median, min & max for each numeric value for each state -- store as new dataframe

cols = [
    "Total Long-term Debt",
    "Total Equity",
    "Debt to Equity",
    "Total Liabilities",
    "Total Revenue",
    "Profit Margin"
]

DF_0[cols] = DF_0[cols].apply(pd.to_numeric)

DF_1 = DF_0.groupby("Business State")[cols].agg(
    ["mean", "median", "min", "max"]
)

In [6]:
DF_1.head()

               Total Long-term Debt                                      \
                               mean      median         min         max
Business State
Alabama                4.931166e+06  5094147.43   445061.52  8075235.91
Alaska                 6.106299e+06  6450485.62  2136032.68  9388192.89
Arizona                4.844419e+06  3660246.50   896096.52  9976915.19
Arkansas               3.375942e+06  3375942.28  1272231.19  5479653.37
California             6.097056e+06  6507490.57  2481327.27  9302349.86

                Total Equity                                       \
                        mean       median         min         max
Business State
Alabama         4.946120e+06  3319659.810  2285238.44  8296102.37
Alaska          3.400092e+06  2996753.015  1980536.22  5626325.36
Arizona         5.356049e+06  5974289.290  3260795.43  6833061.12
Arkansas        4.113534e+06  4113534.330  3017082.34  5209986.32
California      3.126694e+06  2695290.240  2418625.91  4266164.75

               Debt to Equity         ... Total Liabilities              \
                         mean median  ...               min         max
Business State                        ...
Alabama              1.004000  0.990  ...         836241.27  9669535.38
Alaska               2.532500  2.450  ...        4237705.23  7632797.96
Arizona              0.973333  1.120  ...        7333164.02  7857678.40
Arkansas             0.735000  0.735  ...        3174495.93  3815817.93
California           2.280000  2.410  ...        1434547.44  5819738.35

               Total Revenue                                       \
                        mean       median         min         max
Business State
Alabama         5.794423e+06  6054735.020  2903195.17  8745211.56
Alaska          6.569500e+06  6092398.735  4334845.21  9758357.75
Arizona         7.058715e+06  8768954.930  2718406.06  9688783.35
Arkansas        3.376370e+06  3376369.855  1815627.95  4937111.76
California      3.741303e+06  2862263.060  2128936.40  6232710.61

               Profit Margin
                        mean median   min   max
Business State
Alabama             0.822000   0.88  0.65  0.93
Alaska              0.500000   0.52  0.20  0.76
Arizona             0.346667   0.48  0.06  0.50
Arkansas            0.470000   0.47  0.29  0.65
California          0.606667   0.81  0.13  0.88

[5 rows x 24 columns]

In [7]:
#IF debt to equity ratio is negative, remove and save as “DF_2”
DF_2 = DF_0[DF_0[('Debt to Equity')] < 0]
DF_2.head()

Empty DataFrame
Columns: [Business ID, Business State, Total Long-term Debt, Total Equity, Debt to Equity, Total Liabilities, Total Revenue, Profit Margin]
Index: []

In [8]:
#ADD new column “Debt-to-income” WHERE IF total_revenue is 0, return NaN, ELSE divide Long-Term Debt by Revenue
DF_3 = pd.DataFrame({
    'Debt to Income Ratio': np.where(
        DF_0['Total Revenue'] == 0,
        np.nan,
        DF_0['Total Long-term Debt']/DF_0['Total Revenue']
    )
})
DF_3.head()

   Debt to Income Ratio
0              0.073506
1              7.823095
2              4.405687
3              0.407347
4              1.064480

In [9]:
#concat debt to income ratio to original dataframe
DF_Final = pd.concat([DF_0.reset_index(drop=True),DF_3.reset_index(drop=True)],axis=1)
DF_Final.head()

,Business ID,Business State,Total Long-term Debt,Total Equity,Debt to Equity,Total Liabilities,Total Revenue,Profit Margin,Debt to Income Ratio
0,726076597,Alabama,445061.52,2893026.13,0.15,3753563.68,6054735.02,0.93,0.073506
1,165365337,Montana,5592213.55,9933652.59,0.56,9530630.35,714833.95,0.48,7.823095
2,618011676,Delaware,1932069.13,4808866.44,0.40,9462325.86,438539.82,0.53,4.405687
3,425000967,Minnesota,3557010.10,1642178.45,2.17,9623278.75,8732140.37,0.14,0.407347
4,289433882,Indiana,9477883.81,6942758.12,1.37,9878493.86,8903770.44,0.78,1.064480

In [11]:
#export to csv
DF_Final.to_csv(r'Output.csv')
DF_1.to_csv(r'Stats.csv')